<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB as FacadesDB;

class HalamanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
            $suratJuz30 = [
                ['nomor' => 114, 'nama' => 'An-Nas', 'juz' => 30],
                ['nomor' => 113, 'nama' => 'Al-Falaq', 'juz' => 30],
                ['nomor' => 112, 'nama' => 'Al-Ikhlas', 'juz' => 30],
                ['nomor' => 111, 'nama' => 'Al-Lahab', 'juz' => 30],
                ['nomor' => 110, 'nama' => 'An-Nasr', 'juz' => 30],
                ['nomor' => 109, 'nama' => 'Al-Kafirun', 'juz' => 30],
                ['nomor' => 108, 'nama' => 'Al-Kawthar', 'juz' => 30],
                ['nomor' => 107, 'nama' => 'Al-Ma\'un', 'juz' => 30],
                ['nomor' => 106, 'nama' => 'Quraish', 'juz' => 30],
                ['nomor' => 105, 'nama' => 'Al-Fil', 'juz' => 30],
                ['nomor' => 104, 'nama' => 'Al-Humazah', 'juz' => 30],
                ['nomor' => 103, 'nama' => 'Al-\'Asr', 'juz' => 30],
                ['nomor' => 102, 'nama' => 'At-Takathur', 'juz' => 30],
                ['nomor' => 101, 'nama' => 'Al-Qari\'ah', 'juz' => 30],
                ['nomor' => 100, 'nama' => 'Al-\'Adiyat', 'juz' => 30],
                ['nomor' => 99, 'nama' => 'Az-Zalzalah', 'juz' => 30],
                ['nomor' => 98, 'nama' => 'Al-Bayyinah', 'juz' => 30],
                ['nomor' => 97, 'nama' => 'Al-Qadr', 'juz' => 30],
                ['nomor' => 96, 'nama' => 'Al-\'Alaq', 'juz' => 30],
                ['nomor' => 95, 'nama' => 'At-Tin', 'juz' => 30],
                ['nomor' => 94, 'nama' => 'Al-Insyiroh', 'juz' => 30],
                ['nomor' => 93, 'nama' => 'Ad-Dhuha', 'juz' => 30],
                ['nomor' => 92, 'nama' => 'Al-Layl', 'juz' => 30],
                ['nomor' => 91, 'nama' => 'Ash-Shams', 'juz' => 30],
                ['nomor' => 90, 'nama' => 'Al-Balad', 'juz' => 30],
                ['nomor' => 89, 'nama' => 'Al-Fajr', 'juz' => 30],
                ['nomor' => 88, 'nama' => 'Al-Ghashiyah', 'juz' => 30],
                ['nomor' => 87, 'nama' => 'Al-A\'la', 'juz' => 30],
                ['nomor' => 86, 'nama' => 'At-Tariq', 'juz' => 30],
                ['nomor' => 85, 'nama' => 'Al-Buruj', 'juz' => 30],
                ['nomor' => 84, 'nama' => 'Al-Inshiqaq', 'juz' => 30],
                ['nomor' => 83, 'nama' => 'Al-Mutaffifin', 'juz' => 30],
                ['nomor' => 82, 'nama' => 'Al-Infitar', 'juz' => 30],
                ['nomor' => 81, 'nama' => 'At-Takwir', 'juz' => 30],
                ['nomor' => 80, 'nama' => 'Abasa', 'juz' => 30],
                ['nomor' => 79, 'nama' => 'An-Nazi\'at', 'juz' => 30],
                ['nomor' => 78, 'nama' => 'An-Naba', 'juz' => 30],
            ];

            $halamanJuz1 = [
                ['nomor' => 1, 'nama' => 'Bismillahirrahmanirrahim', 'juz' => 1],
                ['nomor' => 2, 'nama' => 'Alif Lam Mim', 'juz' => 1],
                ['nomor' => 3, 'nama' => 'Innal ladzina kafaru', 'juz' => 1],
                ['nomor' => 4, 'nama' => 'Mathaluhum', 'juz' => 1],
                ['nomor' => 5, 'nama' => 'Wabashshiril ladzina', 'juz' => 1],
                ['nomor' => 6, 'nama' => 'Wa idz qala rabbuka', 'juz' => 1],
                ['nomor' => 7, 'nama' => 'Qulna ihbitu', 'juz' => 1],
                ['nomor' => 8, 'nama' => 'Wa idz najjaynakum', 'juz' => 1],
                ['nomor' => 9, 'nama' => 'Wa idz qulna udkhulu', 'juz' => 1],
                ['nomor' => 10, 'nama' => 'Innal ladzina amanu', 'juz' => 1],
                ['nomor' => 11, 'nama' => 'Qalu ud’u lana', 'juz' => 1],
                ['nomor' => 12, 'nama' => 'Awa la ya’lamun', 'juz' => 1],
                ['nomor' => 13, 'nama' => 'Wa idz akhadhna', 'juz' => 1],
                ['nomor' => 14, 'nama' => 'Wa lamma ja’ahum', 'juz' => 1],
                ['nomor' => 15, 'nama' => 'Qul in kanat', 'juz' => 1],
                ['nomor' => 16, 'nama' => 'Wattaba’u ma', 'juz' => 1],
                ['nomor' => 17, 'nama' => 'Ma nansakh', 'juz' => 1],
                ['nomor' => 18, 'nama' => 'Waqalatil yahudu', 'juz' => 1],
                ['nomor' => 19, 'nama' => 'Walan tardha', 'juz' => 1],
                ['nomor' => 20, 'nama' => 'Wa idz yarfa’u', 'juz' => 1],
                ['nomor' => 21, 'nama' => 'Wa qalu kunu', 'juz' => 1],
                ['nomor' => 22, 'nama' => 'Sayaquulu', 'juz' => 2],
                ['nomor' => 23, 'nama' => 'Allaziina Aatayna', 'juz' => 2],
                ['nomor' => 24, 'nama' => 'Walaa Taquuluu', 'juz' => 2],
                ['nomor' => 25, 'nama' => 'Inna Fii Khalqi', 'juz' => 2],
                ['nomor' => 26, 'nama' => 'Wa Izaa Qiila Lahumul', 'juz' => 2],
                ['nomor' => 27, 'nama' => 'Laysal Birra', 'juz' => 2],
                ['nomor' => 28, 'nama' => 'Faman Khaafa', 'juz' => 2],
                ['nomor' => 29, 'nama' => 'Uhilla Lakum', 'juz' => 2],
                ['nomor' => 30, 'nama' => 'Waqtuluuhum', 'juz' => 2],
                ['nomor' => 31, 'nama' => 'Al-Hajju Ashhurun', 'juz' => 2],
                ['nomor' => 32, 'nama' => 'Wazkuruullaha', 'juz' => 2],
                ['nomor' => 33, 'nama' => 'Sal Banii Israa-iil', 'juz' => 2],
                ['nomor' => 34, 'nama' => 'Kutiba Alaykumul', 'juz' => 2],
                ['nomor' => 35, 'nama' => 'Fii Dunyaa Wal Aakhirah', 'juz' => 2],
                ['nomor' => 36, 'nama' => 'Laa Yu-aakhizukumullaahu', 'juz' => 2],
                ['nomor' => 37, 'nama' => 'Wa Izaa Tallaqtumul', 'juz' => 2],
                ['nomor' => 38, 'nama' => 'Wallaziina Yutawaffauna', 'juz' => 2],
                ['nomor' => 39, 'nama' => 'Haafizuu', 'juz' => 2],
                ['nomor' => 40, 'nama' => 'Alam Tara Ilal Malai', 'juz' => 2],
                ['nomor' => 41, 'nama' => 'Falammaa Fasala', 'juz' => 2],

                ['nomor' => 42, 'nama' => 'Tilka al-rusulu', 'juz' => 3],
                ['nomor' => 43, 'nama' => 'Allahu waliyyu', 'juz' => 3],
                ['nomor' => 44, 'nama' => 'Wa idh qala Ibrahimu', 'juz' => 3],
                ['nomor' => 45, 'nama' => 'Wa matsalu alladhina ', 'juz' => 3],
                ['nomor' => 46, 'nama' => 'Wa ma anfaqtum min', 'juz' => 3],
                ['nomor' => 47, 'nama' => 'Alladhina ya\'kuluna', 'juz' => 3],
                ['nomor' => 48, 'nama' => 'Ya ayyuha alladhina', 'juz' => 3],
                ['nomor' => 49, 'nama' => 'Wa in kuntum', 'juz' => 3],
                ['nomor' => 50, 'nama' => 'Bismi Allahi al-Rahmani', 'juz' => 3],
                ['nomor' => 51, 'nama' => 'Inna alladhina kafaru', 'juz' => 3],
                ['nomor' => 52, 'nama' => 'Alladhina yaquluna', 'juz' => 3],
                ['nomor' => 53, 'nama' => 'Alam tara ila', 'juz' => 3],
                ['nomor' => 54, 'nama' => 'Yawma tajidu kullu', 'juz' => 3],
                ['nomor' => 55, 'nama' => 'Hunalika da\'a Zakariyya', 'juz' => 3],
                ['nomor' => 56, 'nama' => 'Wa yukallimu al-nasa fi', 'juz' => 3],
                ['nomor' => 57, 'nama' => 'Rabbana amanna bima', 'juz' => 3],
                ['nomor' => 58, 'nama' => 'Inna hadha lahuwa', 'juz' => 3],
                ['nomor' => 59, 'nama' => 'Ya ahla al-kitabi lima', 'juz' => 3],
                ['nomor' => 60, 'nama' => 'Wa inna minhum lafariqan', 'juz' => 3],

                
                ['nomor' => 61, 'nama' => 'Qul amanna bi Allahi', 'juz' => 3],
                ['nomor' => 62, 'nama' => 'Lan tanalu al-birra', 'juz' => 4],
                ['nomor' => 63, 'nama' => 'Wa kayfa takfuruna ', 'juz' => 4],
                ['nomor' => 64, 'nama' => 'Wa lillahi ma fi', 'juz' => 4],
                ['nomor' => 65, 'nama' => 'Inna alladhina kafaru', 'juz' => 4],
                ['nomor' => 66, 'nama' => 'Idh hammat ta\'ifatani', 'juz' => 4],
                ['nomor' => 67, 'nama' => 'Wa sari\'u ila', 'juz' => 4],
                ['nomor' => 68, 'nama' => 'Wa liyumahhisa Allahu ', 'juz' => 4],
                ['nomor' => 69, 'nama' => 'Ya ayyuha alladhina', 'juz' => 4],
                ['nomor' => 70, 'nama' => 'Thumma anzala \'alaykum', 'juz' => 4],
                ['nomor' => 71, 'nama' => 'Wa la\'in muttum aw', 'juz' => 4],
                ['nomor' => 72, 'nama' => 'Wa ma asabakum yawma', 'juz' => 4],
                ['nomor' => 73, 'nama' => 'Fanqalabu bini\'matin min', 'juz' => 4],
                ['nomor' => 74, 'nama' => 'Laqad sami\'a Allahu', 'juz' => 4],
                ['nomor' => 75, 'nama' => 'Wa idh akhadha Allahu', 'juz' => 4],
                ['nomor' => 76, 'nama' => 'Fastajaba lahum rabbuhum', 'juz' => 4],
                ['nomor' => 77, 'nama' => 'Ya ayyuhan naasu', 'juz' => 4],
                ['nomor' => 78, 'nama' => 'Lilrijali nasibun mimma', 'juz' => 4],
                ['nomor' => 79, 'nama' => 'Wa lakum nisfu', 'juz' => 4],
                ['nomor' => 80, 'nama' => 'Wa allati ya\'tina', 'juz' => 4],
                ['nomor' => 81, 'nama' => 'Wa in aradttumu istibdala', 'juz' => 4],
                ['nomor' => 82, 'nama' => 'Wa al-muhsanatu min', 'juz' => 5],
                ['nomor' => 83, 'nama' => 'Wa Allahu yuridu an', 'juz' => 5],
                ['nomor' => 84, 'nama' => 'Al-rijalu qawwamuna \'ala', 'juz' => 5],
                ['nomor' => 85, 'nama' => 'Wa alladhina yunfiquna ', 'juz' => 5],
                ['nomor' => 86, 'nama' => 'Wa Allahu a\'lamu', 'juz' => 5],
                ['nomor' => 87, 'nama' => 'Ula\'ika alladhina', 'juz' => 5],
                ['nomor' => 88, 'nama' => 'Alam tara ila', 'juz' => 5],
                ['nomor' => 89, 'nama' => 'Wa law anna katabna', 'juz' => 5],
                ['nomor' => 90, 'nama' => 'Wa ma lakum la', 'juz' => 5],
                ['nomor' => 91, 'nama' => 'Man yuti\'i al-rasula', 'juz' => 5],
                ['nomor' => 92, 'nama' => 'Allahu la ilaha', 'juz' => 5],
                ['nomor' => 93, 'nama' => 'Wa ma kana limu\'minin', 'juz' => 5],
                ['nomor' => 94, 'nama' => 'La yastawi', 'juz' => 5],
                ['nomor' => 95, 'nama' => 'Wa idha kunta fihim', 'juz' => 5],
                ['nomor' => 96, 'nama' => 'Wa istaghfiri Allah', 'juz' => 5],
                ['nomor' => 97, 'nama' => 'La khayra', 'juz' => 5],
                ['nomor' => 98, 'nama' => 'Wa alladhina amanu', 'juz' => 5],
                ['nomor' => 99, 'nama' => 'Wa ini imra\'atun khafat', 'juz' => 5],
                ['nomor' => 100, 'nama' => 'Ya ayyuha alladhina', 'juz' => 5],
                ['nomor' => 101, 'nama' => 'Alladhina yatarabbasuna', 'juz' => 5],
                ['nomor' => 102, 'nama' => 'La yuhibbu', 'juz' => 6],
                ['nomor' => 103, 'nama' => 'Fabima naqdihim mithaqahum', 'juz' => 6],
                ['nomor' => 104, 'nama' => 'Inna awhayna', 'juz' => 6],
                ['nomor' => 105, 'nama' => 'Ya ahla al-kitabi la', 'juz' => 6],
                ['nomor' => 106, 'nama' => 'Yastaftunaka quli Allahu', 'juz' => 6],
                ['nomor' => 107, 'nama' => 'Hurrimat \'alaykumul', 'juz' => 6],
                ['nomor' => 108, 'nama' => 'Ya ayyuha alladhina amanu', 'juz' => 6],
                ['nomor' => 109, 'nama' => 'Wa alladhina kafaru', 'juz' => 6],
                ['nomor' => 110, 'nama' => 'Wa mina alladhina qalu', 'juz' => 6],
                ['nomor' => 111, 'nama' => 'Wa qalati al-yahudu', 'juz' => 6],
                ['nomor' => 112, 'nama' => 'Qalu ya Musa inna', 'juz' => 6],
                ['nomor' => 113, 'nama' => 'Min ajli dhalika', 'juz' => 6],
                ['nomor' => 114, 'nama' => 'Yuriduna an yakhruju', 'juz' => 6],
                ['nomor' => 115, 'nama' => 'Samma\'una lil-kadhibi', 'juz' => 6],
                ['nomor' => 116, 'nama' => 'Wa qaffayna', 'juz' => 6],
                ['nomor' => 117, 'nama' => 'Ya ayyuha alladhina', 'juz' => 6],
                ['nomor' => 118, 'nama' => 'Wa idha nadaytum ila', 'juz' => 6],
                ['nomor' => 119, 'nama' => 'Wa law anna ahla', 'juz' => 6],
                ['nomor' => 120, 'nama' => 'Wa hasibu alla takuna', 'juz' => 6],
                ['nomor' => 121, 'nama' => 'Qul ya ahla al-kitabi', 'juz' => 6],
                ['nomor' => 122, 'nama' => 'Wa idha sami\'u ma', 'juz' => 7],
                ['nomor' => 123, 'nama' => 'Ya ayyuha alladhina amanu', 'juz' => 7],
                ['nomor' => 124, 'nama' => 'Uhilla lakum saydu', 'juz' => 7],
                ['nomor' => 125, 'nama' => 'Wa idha qila lahum', 'juz' => 7],
                ['nomor' => 126, 'nama' => 'Yawma yajma\'u', 'juz' => 7],
                ['nomor' => 127, 'nama' => 'Qala \'Isa ibnu', 'juz' => 7],
                ['nomor' => 128, 'nama' => 'Bismi Allahi al-Rahmani', 'juz' => 7],
                ['nomor' => 129, 'nama' => 'Wa law j\'alnahu malakan', 'juz' => 7],
                ['nomor' => 130, 'nama' => 'Qul ayyu shay\'in', 'juz' => 7],
                ['nomor' => 131, 'nama' => 'Bal bada lahum', 'juz' => 7],
                ['nomor' => 132, 'nama' => 'Innama yastajibu', 'juz' => 7],
                ['nomor' => 133, 'nama' => 'Faquti\'a dabiru al-qawmi', 'juz' => 7],
                ['nomor' => 134, 'nama' => 'Wa kadhalika fatanna', 'juz' => 7],
                ['nomor' => 135, 'nama' => 'Wa huwa alladhi', 'juz' => 7],
                ['nomor' => 136, 'nama' => 'Wa ma \'ala alladhina', 'juz' => 7],
                ['nomor' => 137, 'nama' => 'Wa idh qala', 'juz' => 7],
                ['nomor' => 138, 'nama' => 'Alladhina amanu wa lam', 'juz' => 7],
                ['nomor' => 139, 'nama' => 'Wa ma qadaru Allah', 'juz' => 7],
                ['nomor' => 140, 'nama' => 'Inna Allah', 'juz' => 7],
                ['nomor' => 141, 'nama' => 'Dhalikum Allahu', 'juz' => 7]
            ];


        FacadesDB::table('halamans')->insert($suratJuz30);
        FacadesDB::table('halamans')->insert($halamanJuz1);
    }
}
